### ISSUE TITLE
Request: Nerd font support

### ISSUE THREAD

**Issue by Quentin-Mestre** [jacobxperez/lexica-ultralegible#126]
# Feature Request
Is there a plan to add Nerd font support to lexica-ultralegible font ? I wish I could use it as main font for coding and terminal use. 🙏

**Comment by jacobxperez** [comment]
@Quentin-Mestre Do you mean a monospaced version?

**Comment by Quentin-Mestre** [comment]
Yes but also a version patched to include icons as described here : https://www.nerdfonts.com/

**Comment by jacobxperez** [comment]
@Quentin-Mestre - We are currently focused on making Lexica Ultralegible available in as many languages as possible. However, you're welcome to fork the project and patch it with the Nerd Fonts script. We do have plans to create a monospaced version of the font.
